### ISSUE TITLE
element.offsetParent returns null when inside a hidden element

### ISSUE THREAD

**Issue by seanwash** [paulstraw/sundial#2]
Just a quick thing, Im implementing a coupe date pickers in a drawer that can be opened/closed by the user, with the initial state being closed. I noticed that Sundial uses `offsetParent` to attach the `sundial-wrapper` element to the input's parent, however when that parent element is hidden `offsetParent` returns null. I haven't tested a ton, but when I use `parentNode` things work as I expect. Happy to submit a PR if you're cool with it.

**Comment by paulstraw** [comment]
Yeah, sounds good. PR it up!

**Comment by paulstraw** [comment]
Closed by #3
